yanna123@gmail.com- 👋 Hi, I’m @Yannalivia123
- 👀 I’m interested oin ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
Yannalivia123/Yannalivia123 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
